sudo: false
cache:
  directories:
  - "$HOME/.gradle"
language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
script: "./travis-build.sh"
env:
  global:
  - GIT_NAME="Puneet Behl"
  - GIT_EMAIL="behl4485@gmail.com"
  - secure: XKQlMFE+sS9aNhNSR+I6HiF52lBneoCv7nMBzBwjVAI6r8BJ0sSeVUuDLTFI7hUKZAVmYrkYFJkZOA5Exw0KxU8uP6m9Y0xItUNf/zOBgPspm0OtJVGa1FXyDT47IMzc8EGpvGyvYXQDXgCUZFaKNNXq+QvtT1rfFTkflY0//CY=
  - secure: awxvgryU388eMnglUwu2p4qcir9GrdRvUqDN/Sge9/v5kOM6uLow4zoc1qjw+1OGDbkK2uYrHqBzlYtc2OECP7eXxe2h2YleL5KdFgk7NwlcsNfJO6HFJpxxTHctrQWPoXDlTprVsTfqNQjtJRKVu4sqkFOcsWMCqy7HBhsVLws=
  - secure: gbLzvQ7paUpeP/kUVn/e5M38JMy5Sx6UZELKmwnCjmT0dltQacrxJXVSRdSi0l9H/Tr+GeQD9RKhVcMJRKRr3ccJQjQA7cdbaArk00rO5xnGBwI4gh0P4+GodEaScDDCYw6Dl/VtGZzVg6GJQISSV8H2stwgE6XI32M/eZdsyMs=
  - secure: bNIdyqlJ9jIa0ckz7vQRiGKaAcVTYiWn6KOUoo2hi6snt8eD2C333ckrNdULnkaAcEYcpNwvLUyvi/U5ehEpb3W3zrQug2/GHBbjt/kbkubtHzmzP74YN9QVoonp/FjVoHbowy6uYJOGDVaDscp32idb7pvxiViUdVzPbBoZnZw=
  - secure: I1OqbX9lGIuVNvEVCXXYe1ipVkfZaM0Q3WNbtUANApldQ7MrMM5urcdRnN7K3rUE6cAqqh0TfeTn6jZpD3ha+0jQevTG9T0f1TQDagVoE/DrrkWORmZRNK56/nMykoaN2qGxfTBI2bGOiVkcPoIIR7F810GSEzEAimpqFJwDZhw=
  - secure: c9AHc520xT+vhA5wHHW+hD/X1z3/15BDjXxhBclBWIWsIUFi0jeaQphdMffQAhM+BrENH5E5RAX4QU9mSqFmnreb9C9lyP1lIBUIq/IcmHwy3b6WizV9oITpL2kGFh54+fSgQ1PdS0RdUNHhZGJ29WtYsj4KSEY68OR806CsvbQ=
  - secure: VtLOzrRSX80Ytcs/zT+ba/lTyIieMYx2f8dBnyBJTRkU5ik5P01/5a6PQGL1oGoeGkANahpYx0uC1NVxb7IQR2K4tcWswQdtq+pNFaDMW/NMPctz3u+O1Ri5go1HKdgeUxGzIZLfG4ZhmdKVZ9MMO7IJoTjbpZWhFV1TQIZwlHg=
